name: fmtc_example
description: The example application for 'flutter_map_tile_caching', showcasing
  it's functionality and use-cases.
publish_to: "none"

version: 6.2.0+3

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  badges: ^3.1.2
  better_open_file: ^3.6.5
  flutter:
    sdk: flutter
  flutter_foreground_task: ^8.3.0
  flutter_map:
    git:
      url: https://github.com/robpot95/flutter_map.git
      ref: main
  flutter_map_tile_caching:
    path: ../
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.18.1
  latlong2: ^0.9.1
  osm_nominatim: ^3.0.1
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  stream_transform: ^2.1.0
  validators: ^3.0.0
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - currentAppVersion.txt
