name: flutter_map_tile_caching
description: Plugin for 'flutter_map' providing advanced caching functionality,
  with ability to download map regions for offline use.
version: 6.2.0+17
repository: https://github.com/JaffaKetchup/flutter_map_tile_caching
issue_tracker: https://github.com/JaffaKetchup/flutter_map_tile_caching/issues
documentation: https://fmtc.jaffaketchup.dev
publish_to: none

funding:
  - https://github.com/sponsors/JaffaKetchup

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  archive: ^3.5.1
  bezier: ^1.2.0
  collection: ^1.17.1
  cross_file: ^0.3.4+1
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_local_notifications: ^16.3.3
  flutter_map:
    git:
      url: https://github.com/robpot95/flutter_map.git
      ref: main
  http: ^1.2.1
  ini: ^2.1.0
  latlong2: ^0.9.1
  meta: ^1.11.0
  move_to_background: ^1.0.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  queue: ^3.1.0+2
  share_plus: ^7.2.2
  stream_transform: ^2.1.0
  vector_math: ^2.1.4
  watcher: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter: null
